### PR TITLE
bump MMD prereq to parse newer $VERSION syntax

### PR DESCRIPTION
**Pull request by karenetheridge**
https://rt.cpan.org/Ticket/Update.html?id=101095 for details -- bump prereq to ensure this syntax is parsable

Also includes a modeline fix, and an edit I had in a stash for quite a while that simply shortens the code a bit.

### CODE REVIEW

**Comment by Leont** [comment]
You probably want to rebase this first

**Comment by karenetheridge** [comment]
rebased!

**Comment by Leont** [comment]
Looks good to me, you have a commit bit ;-)

**Comment by karenetheridge** [comment]
merged!

**Pull request merged**
